### ISSUE TITLE
Add option to set a base URL name for reverse proxy

### ISSUE THREAD

**Issue by onvrb** [tabarra/txAdmin#158]
I'm running fivem on a docker container and I would like to point my reverse-proxy server to this txAdmin page. 

It would be nice change the base URL setting and point the HTTP root to something like http://localhost:40120/txadmin/

**Comment by tabarra** [comment]
You can do that in your reverse proxy configuration.

**Comment by onvrb** [comment]
The problem is that I don't want it to point to the root domain, I would like to point it to a subfolder.

Anyway, I was able to implement authentication at a subdomain level, so I just used that instead of subfolder for this particular service and I got what I pretended.

But I still would like to know how would you accomplish adding txAdmin on a subfolder without it having a base url.

**Comment by tabarra** [comment]
what is your use case, why do you want to put a rev proxy in front of it?

**Comment by onvrb** [comment]
use organizr (https://github.com/causefx/Organizr) authentication layer and also SSL from letsencrypt container.

2 reasons for not using cfx's SSL:
-privacy, I prefer using my own SSL certs
-can't even connect through them in the first place, and no guarantees they will have a reliable uptime.

**Comment by tabarra** [comment]
Well, then I guess you have an pretty edge case.  
Although the SSL on the non-cfx.re url would be a good feature to be re-added to txAdmin (v1 had this), I don't think this will be in the roadmap anytime ever.  
  
Also, what's wrong with txAdmin's auth layer?  
Anyways, closing this since its not relevant to anybody else.
