### ISSUE TITLE
Can't choose warning messages as before (disabled) and locale has no effect on the warning languages

### ISSUE THREAD

**Issue by TsxMax** [tabarra/txAdmin#428]
Hi,
I used to commonly use command txawarnid with params such as : 
```txawarnid id author reason tTitle tWarnedBy tInstruction```

In a previous commit, usage of params tTitle, tWarnedBy, tInstruction have been disabled
I then changed the locale to my language in the txAdmin web interface, but this has no effect, neither on the web user interface menus, nor on the game UI.
So my players keep having the message "Warning" and "Hold Space for 10 seconds..." instead of the translated strings.

Any idea to get the tTitle, tWarnedBy and tInstruction in the language I want OR with custom strings like before ?
Thanks !
Max

**Comment by tabarra** [comment]
Hey. That command is an internal command not meant to be used by humans, so no backwards compatibility guaranteed.  
The warn is now part of the menu, and the menu translation is disable for now.  
  
I see this as part of another in-progress issue, so i'm closing it but feel free to add any comments.

**Comment by TsxMax** [comment]
Thanks for your answer tabarra
