### ISSUE TITLE
[Feature]: Localization

### ISSUE THREAD

**Issue by Justman10000** [tabarra/txAdmin#460]
### Scope

Web

### Feature Description

A localization system that enables txAdmin to be multilingual...

### Additional Info

The best example is the [Azuriom website](https://azuriom.com) ([Github](/Azuriom/azuriom.com))

**Comment by tabarra** [comment]
Sorry, but **for us** this is just not possible. Would be a terrible strategy.  
Right now we (mostly I) can't even keep up with the things we need to do (menu was supposed to be out of beta two months ago), having to deal with interface translation is virtually impossible.  
  
Also who would translate everything? The community in general does a terrible job.  
Who would give support to those people with error messages in those languages?  
I could literally ask like 20 questions that show how much this is not viable for us.  
  
Sorry.

**Comment by Justman10000** [comment]
> 
> 
> Sorry, but **for us** this is just not possible. Would be a terrible strategy. Right now we (mostly I) can't even keep up with the things we need to do (menu was supposed to be out of beta two months ago), having to deal with interface translation is virtually impossible.
> 
> Also who would translate everything? The community in general does a terrible job. Who would give support to those people with error messages in those languages? I could literally ask like 20 questions that show how much this is not viable for us.
> 
> Sorry.

Well, personally I would add German completely... Hence the suggestion...

**Comment by Justman10000** [comment]
@tabarra
