### ISSUE TITLE
[BUG] External DB connection settings not working during deployer

### ISSUE THREAD

**Issue by BlackDahlia313** [tabarra/txAdmin#462]
**txAdmin/FXServer versions:**
4.6.1 // 4748
  
**Describe the bug**
When using the recipe deployer, you cannot use an external DB. No matter what you type, it tries to use localhost.

**To Reproduce**
1. ResetFX
2. Use any receipe (I used qbcore)
3. Expand advanced db connection
4. Try to use an external IP/Hostname
5. It says cant connect to localhost 

**Expected behavior**
Connect to external DB for deployment

**Comment by tabarra** [comment]
Can you record a video of this? I just tried on localhost with a remote connection (my zap server) and it just worked.  
https://streamable.com/q2roqq

**Comment by tabarra** [comment]
closing it due to lack of evidence.
