### ISSUE TITLE
[BUG] Light Mode Bug

### ISSUE THREAD

**Issue by odwales20** [tabarra/txAdmin#472]
Server log Bug on light Mode 
![image](https://user-images.githubusercontent.com/71227962/137638180-7cc97f68-e927-4860-a21f-54fee6263410.png)
![image](https://user-images.githubusercontent.com/71227962/137638193-9b7139fa-1804-4d15-bebf-fae7fc31303e.png)

**Comment by n0tsiege** [comment]
A fix was pushed at https://github.com/tabarra/txAdmin/commit/c3e16024e606910b982b6680a931aa54b7cb9ed2
