### ISSUE TITLE
[BUG] I cannot Join discord server !!!

### ISSUE THREAD

**Issue by subhampro** [tabarra/txAdmin#931]
![image](https://github.com/tabarra/txAdmin/assets/33375250/e5b6a74c-22e2-4037-a6b3-856141384c3d)

I tried to join your discord server ! But unable to join IDK why ! please Fix this !!

Discord Username : subhamproyt
Discord User ID : 451231838229495828

**Comment by tabarra** [comment]
You were banned.  
I've removed your ban, please behave.
